In [2]:
import numpy as np
import pandas as pd 
#yüklediğimiz veri setini okuyoruz
df=pd.read_csv("cumulative.csv")

df.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [3]:
#hedef sütunumuz olan koi_disposition sütunundaki hedef değişkenlerin sayılarını buluyoruz.
df["koi_disposition"].value_counts()
#aday olarak işaretlenmiş CANDIDATE değişkenlerini çıkartıp df_filtered isimli yeni bir tablo oluşturuyoruz.
df_filtered=df[df["koi_disposition"]!='CANDIDATE']
df_filtered.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [4]:
df_filtered["koi_disposition"].value_counts()

koi_disposition
FALSE POSITIVE    5023
CONFIRMED         2293
Name: count, dtype: int64

In [5]:
#mapping değişkeni ile bir python sözlüğü oluşturup alttaki güncelleme fonksiyonu olan map() fonksiyonuna parametre olarak veriyoruz.
mapping={"FALSE POSITIVE":0,"CONFIRMED":1}
df_filtered['koi_disposition']=df_filtered['koi_disposition'].map(mapping)
df_filtered.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,1,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,1,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,0,FALSE POSITIVE,0.000,0,1,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,0,FALSE POSITIVE,0.000,0,1,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,1,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [6]:

df_filtered.isnull().sum()

rowid                   0
kepid                   0
kepoi_name              0
kepler_name          5022
koi_disposition         0
koi_pdisposition        0
koi_score            1059
koi_fpflag_nt           0
koi_fpflag_ss           0
koi_fpflag_co           0
koi_fpflag_ec           0
koi_period              0
koi_period_err1       377
koi_period_err2       377
koi_time0bk             0
koi_time0bk_err1      377
koi_time0bk_err2      377
koi_impact            300
koi_impact_err1       377
koi_impact_err2       377
koi_duration            0
koi_duration_err1     377
koi_duration_err2     377
koi_depth             300
koi_depth_err1        377
koi_depth_err2        377
koi_prad              300
koi_prad_err1         300
koi_prad_err2         300
koi_teq               300
koi_teq_err1         7316
koi_teq_err2         7316
koi_insol             259
koi_insol_err1        259
koi_insol_err2        259
koi_model_snr         300
koi_tce_plnt_num      279
koi_tce_delivname     279
koi_steff             300
koi_steff_err1        397
koi_steff_err2        412
koi_slogg             300
koi_slogg_err1        397
koi_slogg_err2        397
koi_srad              300
koi_srad_err1         397
koi_srad_err2         397
ra                      0
dec                     0
koi_kepmag              1
dtype: int64

In [7]:
columns_to_drop=['rowid', 'kepid', 'kepoi_name', 'kepler_name', 'koi_score','koi_pdisposition']
df_filtered=df_filtered.drop(columns_to_drop,axis=1)

In [8]:
# 1. İçinde 'err' geçen kolonları otomatik bul ve bir listeye at
err_columns = [col for col in df_filtered.columns if 'err' in col]

# 2. Bulunan bu kolonları veri setinden (sütun ekseninde, axis=1) düşür
df_filtered = df_filtered.drop(err_columns, axis=1)

# 3. Kalan saf fiziksel verilerdeki (az sayıdaki) eksik satırları tamamen sil
df_filtered = df_filtered.dropna(axis=0)

# Sonuca bakalım
df_filtered.head()

,koi_disposition,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_time0bk,koi_impact,koi_duration,koi_depth,...,koi_insol,koi_model_snr,koi_tce_plnt_num,koi_tce_delivname,koi_steff,koi_slogg,koi_srad,ra,dec,koi_kepmag
0,1,0,0,0,0,9.488036,170.538750,0.146,2.95750,615.8,...,93.59,35.8,1.0,q1_q17_dr25_tce,5455.0,4.467,0.927,291.93423,48.141651,15.347
1,1,0,0,0,0,54.418383,162.513840,0.586,4.50700,874.8,...,9.11,25.8,2.0,q1_q17_dr25_tce,5455.0,4.467,0.927,291.93423,48.141651,15.347
2,0,0,1,0,0,19.899140,175.850252,0.969,1.78220,10829.0,...,39.30,76.3,1.0,q1_q17_dr25_tce,5853.0,4.544,0.868,297.00482,48.134129,15.436
3,0,0,1,0,0,1.736952,170.307565,1.276,2.40641,8079.2,...,891.96,505.6,1.0,q1_q17_dr25_tce,5805.0,4.564,0.791,285.53461,48.285210,15.597
4,1,0,0,0,0,2.525592,171.595550,0.701,1.65450,603.3,...,926.16,40.9,1.0,q1_q17_dr25_tce,6031.0,4.438,1.046,288.75488,48.226200,15.509

In [9]:
#lineer cebirdeki gibi bir özellikler(X) ve hedef(y) matrisleri oluşturuldu.

y=df_filtered['koi_disposition'] 
X=df_filtered.drop(['koi_disposition'],axis=1)
y.head()
X.head()

,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_time0bk,koi_impact,koi_duration,koi_depth,koi_prad,...,koi_insol,koi_model_snr,koi_tce_plnt_num,koi_tce_delivname,koi_steff,koi_slogg,koi_srad,ra,dec,koi_kepmag
0,0,0,0,0,9.488036,170.538750,0.146,2.95750,615.8,2.26,...,93.59,35.8,1.0,q1_q17_dr25_tce,5455.0,4.467,0.927,291.93423,48.141651,15.347
1,0,0,0,0,54.418383,162.513840,0.586,4.50700,874.8,2.83,...,9.11,25.8,2.0,q1_q17_dr25_tce,5455.0,4.467,0.927,291.93423,48.141651,15.347
2,0,1,0,0,19.899140,175.850252,0.969,1.78220,10829.0,14.60,...,39.30,76.3,1.0,q1_q17_dr25_tce,5853.0,4.544,0.868,297.00482,48.134129,15.436
3,0,1,0,0,1.736952,170.307565,1.276,2.40641,8079.2,33.46,...,891.96,505.6,1.0,q1_q17_dr25_tce,5805.0,4.564,0.791,285.53461,48.285210,15.597
4,0,0,0,0,2.525592,171.595550,0.701,1.65450,603.3,2.75,...,926.16,40.9,1.0,q1_q17_dr25_tce,6031.0,4.438,1.046,288.75488,48.226200,15.509

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = X.select_dtypes(include=['number'])
X_scaled=scaler.fit_transform(X)
print("Ölçeklendirilmiş matrisin boyutu:", X_scaled.shape)

Ölçeklendirilmiş matrisin boyutu: (6809, 20)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,stratify=y,random_state=42)
print("Eğitim seti (Sorular):", X_train.shape)
print("Test seti (Sinav):", X_test.shape)

Eğitim seti (Sorular): (5447, 20)
Test seti (Sinav): (1362, 20)

In [12]:
from sklearn.linear_model import LogisticRegression


log_model = LogisticRegression(random_state=42)

log_model.fit(X_train, y_train)

print("Model başariyla eğitildi!")

Model başariyla eğitildi!

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred=log_model.predict(X_test)
acc=accuracy_score(y_test,y_pred)
print(f"modelin basari yüzdesi ={acc*100}")
confusion_matrix(y_test,y_pred)

modelin basari yüzdesi =98.89867841409692

array([[904,   1],
       [ 14, 443]])

In [14]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(random_state=42)
rf_model.fit(X_train,y_train)
print("RandomForest Modeli başariyla eğitildi!")

RandomForest Modeli başariyla eğitildi!

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred2=rf_model.predict(X_test)
acc2=accuracy_score(y_test,y_pred2)
print(f"modelin basari yüzdesi : {acc2*100}")
confusion_matrix(y_test,y_pred2)

modelin basari yüzdesi : 98.75183553597651

array([[905,   0],
       [ 17, 440]])

In [16]:
from sklearn.model_selection import cross_val_score
arr=cross_val_score(rf_model,X_scaled,y,cv=5)
x=1
sum=0
for i in arr:
    print(f"{x}'nci testin sonucu {i}")
    x=x+1
    sum=sum+i
avg=sum/5
print(f"5 testin ortalamasi:{avg}")

1'nci testin sonucu 0.9919236417033774
2'nci testin sonucu 0.9889867841409692
3'nci testin sonucu 0.9889867841409692
4'nci testin sonucu 0.9941262848751835
5'nci testin sonucu 0.9772226304188097
5 testin ortalamasi:0.9882492250558619

In [17]:
from sklearn.model_selection import GridSearchCV


param_grid={'n_estimators':[50, 100, 200],'max_depth':[None, 10, 20]}
grid_search=GridSearchCV(estimator=rf_model,param_grid=param_grid,cv=5,n_jobs=-1)
grid_search.fit(X_train, y_train)
print(grid_search.best_params_)

{'max_depth': None, 'n_estimators': 200}

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix
rf_best_model=grid_search.best_estimator_
y_pred_best=rf_best_model.predict(X_test)
acc_best=accuracy_score(y_test,y_pred_best)
print(acc_best)
confusion_matrix(y_test,y_pred_best)

0.9882525697503671

array([[905,   0],
       [ 16, 441]])

In [19]:
import joblib


pipeline_data = {
    'model': rf_best_model,
    'scaler': scaler,
    'features': X.columns.tolist()
}


joblib.dump(pipeline_data, 'kepler_pipeline.joblib')

print("Model, Scaler ve Kolon isimleri başariyla bilgisayara kaydedildi.")

Model, Scaler ve Kolon isimleri başariyla bilgisayara kaydedildi.